[theme]
primaryColor = "#006B4F"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f6f300"
textColor = "#16352D"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
