[theme]
primaryColor = "#006B4F"
backgroundColor = "#ffffff00"
secondaryBackgroundColor = "#F0F6F3"
textColor = "#16352D"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
